### ISSUE TITLE
Discussion on the new requriment

### ISSUE THREAD

**Issue by CCSCovenant** [CCSCovenant/TAB2XML#10]
1.The system must allow the user to customize the visual output to improve it aesthetically and functionally. This definitely includes adjusting the spacing between notes in order to have both the left and right ends of the output align (similar to text justification in a word processor). It can also include customizing fonts, the spacing between the lines of the staff, the size of the notes etc.

2.Repeats must be supported as well. Try [this example](https://wiki.eecs.yorku.ca/course_archive/2021-22/W/2311/_media/repeat.txt) input on MuseScore to see the expected output.

3.The previewer should allow the user to see what measure number they are looking at, as well as support a Go To Measure function as in the text input.

4.The play function must allow the user to change the tempo of the music, i.e. how fast or slow it is played back. This must be expressed in beats per minute (bpm). 60 bpm means that there are 60 quarter notes in a minute, i.e. each quarter note lasts one second.

5.There must be a connection between the play function and the visual output as follows: The user must be able to select a measure (or a note) and start playback from that point. Also, when the music is playing, the visual output must highlight the note that is currently being played (similar to MuseScore).

**Comment by CCSCovenant** [comment]
for 1 we have done it already. need a gui for user

for 2 and 4 we only need a little modify in player

for the 3 and 5, i suggest use a canvas as a overlay to draw high-light things

for the 5.maybe we have to rewrite the player things
we should use real-time player in jfugue that will fire event when things is playing

**Comment by CCSCovenant** [comment]
@mbhsiddiqui @Kamsi-idimogu @hiba7868

**Comment by Kamsi-idimogu** [comment]
Requirement 2 has been taken care of from my recent commit, our project now supports repeats.

**Comment by CCSCovenant** [comment]
development parse is done.
