### ISSUE TITLE
Wrong Window Title for Preview Sheet Music

### ISSUE THREAD

**Issue by MahdiarShoraka** [CCSCovenant/TAB2XML#11]
Description: Window Title for Preview Sheet Music is "preview musicXML" as opposed to "preview sheet music".

Version: 1.3 Pre-release / master branch (.jar file didn't work properly so I Imported the master branch to Eclipse)

Platform: Windows – Eclipse IDE - Gradle Execution

Reproduction: Run the application. Give some valid input txt file. Click on preview Sheet Music.

Expected: "preview sheet music"

Actual: 

![Screenshot (182)](https://user-images.githubusercontent.com/74324064/159708560-b6802d20-e5e9-4a4e-a168-001c948acb78.png)

Priority: 2/5

Severity: 1/5 (doesn't affect anything important)

**Comment by CCSCovenant** [comment]
thanks for your participation
it is working as intended.
