### ISSUE TITLE
Unwanted Changes in PDF version of Sheet Music

### ISSUE THREAD

**Issue by MahdiarShoraka** [CCSCovenant/TAB2XML#12]
Description: Measure Numbers are different compared to the original version of the sheet music.

Version: 1.3 Pre-release

Platform: Windows – Eclipse IDE - Gradle Execution

Reproduction: Run the application. Open [bendTest1.txt](https://github.com/CCSCovenant/TAB2XML/files/8333382/bendTest1.txt) as the input. Click on Preview Sheet Music. Click on Export as PDF. You have to **export the file twice** to see this bug, The first downloaded file shows the correct measure numbers, but when you download the file again, measure numbers increase. In the third attempt, you will get 5 and 6 instead of 1 and 2.
(Take a look at Issue #13 . This might be the cause of this issue as well)

Expected: 

![Screenshot (183)](https://user-images.githubusercontent.com/74324064/159710918-bcc62a45-fb5b-4e6d-9c18-7d5e433728bb.png)

Actual: (Look at the highlighted areas)

![Screenshot (185)](https://user-images.githubusercontent.com/74324064/159711447-d135031e-7ecc-4634-96a6-7fb13a790edc.png)

Priority: 3/5

Severity: 2/5

**Comment by CCSCovenant** [comment]
thanks for your participation
this bug has been fixed in the latest commit
we will release the new jar file when another part of the program is finished
