### ISSUE TITLE
Not able to Export the Sheet Music as type ".pdf"

### ISSUE THREAD

**Issue by MahdiarShoraka** [CCSCovenant/TAB2XML#13]
Description: When a user tries to Export as PDF, Save as Window opens. In this stage, the user should be able to save the file as .pdf to be able to easily open the file later with compatible PDF readers e.g., Adobe Acrobat Reader. However, the user is not able to select type as .pdf.
(For more details take a look at the provided screenshot)

Version: 1.3 Pre-release / the last commit (.jar file didn't work properly, so I had to import the latest commit of the master branch to Eclipse) 

Platform: Windows

Reproduction: Run The application. Open any compatible text input. Click on Preview Sheet Music. Click on Export as PDF. When the "Save as" Window opens, click on the "Save as type" bar.

Expected: 

There should be .pdf option in the "Save as type" bar.

Actual:

![Screenshot (187)](https://user-images.githubusercontent.com/74324064/159715095-612fde71-5dff-4ea5-a27b-04ec44c6ae4a.png)

Priority: 4/5

Severity: 3/5

**Comment by CCSCovenant** [comment]
this bug has been fixed in 2.0 release
