### ISSUE TITLE
Long Measures are Cut Off in Preview and Exported PDF

### ISSUE THREAD

**Issue by prabjot09** [CCSCovenant/TAB2XML#14]
### Description: 
When the length of a single measure exceeds the width of the PDF/preview screen, the measure will be cut off. So only the portion of the measure fitting on the screen is displayed.

### Version: release-1.3
https://github.com/CCSCovenant/TAB2XML/releases/tag/pre-release-1.3 

### Required Input:
[longMeasureCutOffBugTest.txt](https://github.com/CCSCovenant/TAB2XML/files/8333616/longMeasureCutOffBugTest.txt)

### Steps to Reproduce:
1. Initiate the application (via Eclipse or the released .jar file)
2. Copy the text from the provided file in the "Required Input" section.
3. Paste the text into the text field of the application and click "Preview Sheet Music"
4. Scroll to the right on the new pop-up window and the bug will be visible.

### Expected Output:
The measure is condensed enough to fit within the limits of the page.
![image](https://user-images.githubusercontent.com/77180065/159717603-6ab4e257-23f6-4c21-aa23-77c5b949bed5.png)

### Actual Output:
The measure is cut off due to the length being too long to fit on the page.
![image](https://user-images.githubusercontent.com/77180065/159718321-7e2c19b6-e47a-4f89-bebd-4ade681ad22f.png)

#### Severity: Low
Has little impact over the whole output and no impact to the functionality of the application. Only a very small portion of the sheet music is obscured.
#### Recommended Priority: Low
Very unlikely that a single measure will be so long that it can't fit the size of the page.

**Comment by CCSCovenant** [comment]
thanks for your participation
this bug has been fixed with a zoomable view windows in the latest commit
we will release the new jar file when another part of the program is finished
