### ISSUE TITLE
Inconsistent/Missing Grace Note Arcs

### ISSUE THREAD

**Issue by prabjot09** [CCSCovenant/TAB2XML#15]
### Description:
For some grace notes, there are no arcs which extends from the grace note to the regular note. There is a recurring pattern that if _**n**_ grace notes come before a regular note, then there are only _**(n-1)**_ arcs displayed. The arc from the last grace note to the regular note is missing. 
_The concept of this bug will be more clear in the provided examples below._

### Version: release-1.3
https://github.com/CCSCovenant/TAB2XML/releases/tag/pre-release-1.3

### Required Input:
[MissingGraceBugTest.txt](https://github.com/CCSCovenant/TAB2XML/files/8333911/MissingGraceBugTest.txt)
(The measures in this file have been abbreviated from the "capricho.txt" file)

### Steps to Reproduce:
1. Run the application (via Eclipse Gradle Tasks or the released .jar file)
2. Copy the text from the file provided in the "Required Input" section.
3. Paste the text into the text field of the application, and click "Preview Sheet Music"
4. Observe the bug on the new window that has popped up. Compare with the result in MuseScore.

### Expected Result:
For each grace note, there is 1 arc. In this example, there must be 1 arc in Measure 1, 2 arcs in Measure 2, and 3 arcs in Measure 3.
![image](https://user-images.githubusercontent.com/77180065/159724131-a7607104-343b-419e-8719-8c5d215ec875.png)

### Actual Result:
There is always 1 missing arc, the arc which extends from the last grace note to the regular note.
![image](https://user-images.githubusercontent.com/77180065/159724477-2d0e3018-193a-447c-9f45-6e5858d74dc0.png)

#### Severity: Low
This does not significantly impact the rest of the notes in the measure or the formatting.
#### Priority: Medium
Grace notes are fairly common especially in longer measures such as in the "capricho.txt", so this bug should be addressed fairly soon.

**Comment by CCSCovenant** [comment]
this bug has been fixed in 2.0 release
