### ISSUE TITLE
BUG in saved PDF

### ISSUE THREAD

**Issue by Baye0110** [CCSCovenant/TAB2XML#16]
**BUG ID:** #16

**DESCRIPTION:** After I exported PDF, and the measure number in PDF is different from the original music sheet

**TITLE:**  BUG in saved PDF

**SUBMITTER:** Yongjie Ba

**VERSION:** 
     Eclipse 2021-12 (4.22.0)
     Gradle: 7.1.1
     Java 17
     Branch: Master(9fb83e4)

**PLATFORM:**
Windows 10 Home (Version: 21H1)

**REPRODUCTION:** 
Open the application: Gradle Tasks -> TABXML_G14 -> application-> run
After opening the Application:
1.	Click file-open and choose the bendTest1 txt file to follow the path “src/test/resources/system”
2.	Then Click Preview Sheet Music Button
3.	Click Export PDF Button
4.	Save the file with a valid name as of PDF version
5.	Click the saved PDF and you will see the bug

**EXPECTED:**  the whole part of the music sheet
 
![image](https://user-images.githubusercontent.com/90529080/159801856-22ea2394-7a86-4e92-98d5-3a492a1bfcfe.png)

**ACTUAL:**  the measure number is different from the original music sheet, the position still follows the end of the original one
![image](https://user-images.githubusercontent.com/90529080/159801967-41a89fb4-c79d-4c61-a144-c731bcbe9f0a.png)
**PRIORITY:**  High Priority

**SEVERITY:** Medium severity
May influence user experience

**Comment by CCSCovenant** [comment]
this bug has been fixed in 2.0 release
