### ISSUE TITLE
Tie Test bug

### ISSUE THREAD

**Issue by Baye0110** [CCSCovenant/TAB2XML#17]
**BUG ID:** #17

**DESCRIPTION:**  Tie test not passed; the tie of the symbol is not displayed correctly

**TITLE:**  Tie Test bug

**SUBMITTER:** Yongjie Ba

**VERSION:** 
     Eclipse 2021-12 (4.22.0)
     Gradle: 7.1.1
     Java 17
     Branch: Master(9fb83e4)

**PLATFORM:**
Windows 10 Home (Version: 21H1)

**REPRODUCTION:** 
Open the application: Gradle Tasks -> TABXML_G14 -> application-> run
After opening the Application:
1.	Click file-open and choose the Tie test txt file to follow the path “src/test/resources/system”
2.	Then Click Preview Sheet Music Button and you may see bugs
**EXPECTED:** Tie connection shows correctly
 
![image](https://user-images.githubusercontent.com/90529080/159798577-e24e7429-e3e5-4675-b49d-2e129c9851b0.png)

**ACTUAL:**  lack of tie connection
 
![image](https://user-images.githubusercontent.com/90529080/159798590-c7a3567e-8210-4d29-9561-570be2ad34b5.png)

**PRIORITY:**  Medium Priority

**SEVERITY:** low severity
 May influence user experience especially to the musicians

**Comment by CCSCovenant** [comment]
this bug has been fixed in 2.0 release
