### ISSUE TITLE
Grace test bug

### ISSUE THREAD

**Issue by Baye0110** [CCSCovenant/TAB2XML#18]
**BUG ID:** #18

**DESCRIPTION:**  when I try to make a grace test and the output lack slur notation compared with the expectation version.

**TITLE:**   Grace test bug

**SUBMITTER:** Yongjie Ba

**VERSION:** 
     Eclipse 2021-12 (4.22.0)
     Gradle: 7.1.1
     Java 17
     Branch: Master(9fb83e4)

**PLATFORM:**
Windows 10 Home (Version: 21H1)

**REPRODUCTION:** 
Open the application: Gradle Tasks -> TABXML_G14 -> application-> run
After opening the Application:
1.	Click file-open and choose the graceTest1 txt file to follow the path “src/test/resources/system”
2.	Click the Preview Sheet Music Button and then you can see the bug

**EXPECTED:**    two slurs between (4 and 16) and (16 and 5) in first notation
 
![image](https://user-images.githubusercontent.com/90529080/159804762-61c5b87a-9117-46f8-9c4c-2bd30b68db58.png)

**ACTUAL:**  lack of slur notation between 16 and 5
 
![image](https://user-images.githubusercontent.com/90529080/159804768-0dfd6ff2-d136-400e-a9bf-953a29d0dd43.png)

**PRIORITY:**  Medium Priority

**SEVERITY:** low severity

**Comment by CCSCovenant** [comment]
this bug has been fixed in 2.0 release
