### ISSUE TITLE
noteWidth Config Making Sheet Music Unreadable

### ISSUE THREAD

**Issue by ksingh0** [CCSCovenant/TAB2XML#19]
Who Raised: Kris Singh

Description: When using the noteWidth config option and setting it to the maximum value of 12.0, the physical radius of the notes made them so large such that its difficult to determine where on the staff they are supposed to be, meaning it is difficult or even impossible to determine what certain notes are supposed to be.

Version: Master branch as of March 23rd, 2022 (Jar file did not work so I had to manually import the master)
Platform: Windows | Eclipse

Reproduction: Enter any valid drum tablature, example 
CC|x---------------|--------x-------|
HH|--x-x-x-x-x-x-x-|----------------|
SD|----o-------o---|oooo------------|
HT|----------------|----oo----------|
MT|----------------|------oo--------|
BD|o-------o-------|o-------o-------|
Next, click on "Preview Sheet Music", then go to the config menu and select "noteWidth". After that, simply select the option of 12.0 from the value menu and click on "apply config" (side note but please properly capitalize these options and buttons for professionalism.)

Expected: To begin with, I am unsure of how the noteWidth option is supposed to work, but from what I've seen, the intended use is to increase the width size of the circular portions of the notes, not the height.

Actual: Both the width and height of the notes are increased, resulting in large notes that the user is unable to determine where they go.

Priority: 3/5
Severity: 2/5 (Since the user can always change it back)

Screenshots:
![image](https://user-images.githubusercontent.com/77803965/159807831-37a1671b-2bbb-4e4f-8610-f5d89bb6b13b.png)

**Comment by CCSCovenant** [comment]
this bug has been fixed in 2.0 release
