### ISSUE TITLE
Staff Going Offscreen

### ISSUE THREAD

**Issue by ksingh0** [CCSCovenant/TAB2XML#20]
Who Raised: Kris Singh

Description: When testing different tablatures, I found an instance where the staff goes offscreen, meaning the user might not know if certain notes go offscreen or not.

Version: Master branch as of March 23rd, 2022
Platform: Windows | Eclipse

Reproduction: Launch the application and open the [capricho.txt](https://github.com/CCSCovenant/TAB2XML/files/8337151/capricho.txt) file located in source/test/resources/system/capricho.txt
Next, click the "Preview Sheet Music" button. Instantly on the first page, you can see the staff going offscreen on the 5th line at bar 11.

Expected: 
![image](https://user-images.githubusercontent.com/77803965/159810109-5e896315-e5c7-455a-9526-a583a3ee8d7f.png)

Actual: 
![image](https://user-images.githubusercontent.com/77803965/159810129-feea8b19-c9cd-4726-a721-f7ee73750d0e.png)
(Note - even sliding the bottom slider fully to the right does not reveal the end of the staff)

Priority: 4/5
Severity: 4/5

Screenshots: Attached above.

**Comment by CCSCovenant** [comment]
this bug has been fixed in 2.0 release
