### ISSUE TITLE
Longer Drum Tablature Causing Sheet Music to Freeze When Changing Configs

### ISSUE THREAD

**Issue by ksingh0** [CCSCovenant/TAB2XML#21]
Who Raised: Kris Singh

Description: When using a lengthier piece of drum tablature, the entire application freezes when attempting to change configs like the noteWidth.

Version: Master branch as of March 23rd, 2022
Platform: Windows | Eclipse

Reproduction: Launch the application and open the [parabola.txt](https://github.com/CCSCovenant/TAB2XML/files/8337206/parabola.txt) file located in source/test/resources/system/parabola.txt
Next, click the "Preview Sheet Music" button and select noteWidth in configs and attempt changing it to 9.0. This causes the program to freeze.

Expected: The program is not meant to freeze and is supposed to change the note width normally.

Actual: The program freezes upon clicking apply config.

Priority: 5/5
Severity: 5/5

Screenshots: 
![image](https://user-images.githubusercontent.com/77803965/159811463-15d6e166-5e81-4e76-9a62-7e6237f628f0.png)

**Comment by CCSCovenant** [comment]
this bug has been fixed in 2.0 release
