### ISSUE TITLE
Music Playback restarted with Play Button

### ISSUE THREAD

**Issue by prabjot09** [CCSCovenant/TAB2XML#22]
### Description: 
The play button does initially start the music playback, but if it is pressed again during the music playback, then the music will start playing from the beginning. Since the button is simply named "Play" it is misleading that it always plays from the beginning which is expected from a "Play from Start".

### Version: release-1.3
https://github.com/CCSCovenant/TAB2XML/releases/tag/pre-release-1.3

### Required Input:
Any valid tablature input would suffice, but the following text file is particularly useful because it always begins with the easily recognizable cymbal sound: [PlayFromStartBugTest.txt](https://github.com/CCSCovenant/TAB2XML/files/8337219/PlayFromStartBugTest.txt)

### Steps to Reproduce:
1. Run the application (via Gradle Tasks or the released .jar file)
2. Copy the text in the provided file in the "Required Input" section.
3. Paste the text into the text field of the application and click "Preview Sheet Music"
4. On the new window that has popped up displaying the sheet music, click "Play".
5. Continue to click "Play" every 3 seconds. Notice that the music playback starts from the beginning.

### Expected Result:
Either **(1)** nothing occurs on pressing the "play" button while the music is already playing, or **(2)** the Play button works as a toggle to pause and play the music.

### Actual Result:
The music is played from the start of the score, when the Play button is clicked even when the music is in the middle of playing the score.

#### Severity: Medium
Doesn't ruin the rest of the program, but does significantly disturb the music playback especially for longer scores.
#### Priority: Low
This can easily be fixed alongside the new requirements where new functionality will be added such as a "Pause" and a "Play from Specified Note" functionality are implemented. Once the user is aware of this bug, they can avoid its occurrence.

**Comment by CCSCovenant** [comment]
this bug has been fixed in 2.0 release
