### ISSUE TITLE
Additional Feedback On Release 1.3

### ISSUE THREAD

**Issue by prabjot09** [CCSCovenant/TAB2XML#23]
_[Note: This Issue doesn't specify a bug, but it is general feedback on the current implementation of the system.]_

1. The "Previous/Next Page" feature are nice to have, it may be useful to allow the client the choice whether they want the whole sheet on 1 page, or on multiple

2. When the "Next/Previous Page" buttons are clicked, the scrollbar remains in the same position as the last page (If the user was looking at the bottom of the page, if they go to the next page they will see the bottom of the next page). It may be more intuitive to show the top of the page when going to the next page. And showing the bottom of the previous page.

3. The slides functionality is currently not implemented (these are the straight lines which connect the notes on the guitar). These also must be implemented in the play functionality (they sound like they quickly play each note between 2 notes). To see an example of this, play measure 10 of "capricho.txt" on MuseScore. The slide occurs between the 2nd and 3rd notes.

4. For the configs, it would be useful to the user to see the current value of the configuration (since the "value" box is empty by default. And if you switch the configuration type (ex. change from measureGap to stepSize), then the "value" box also goes blank)

5. The naming of the configs can be done in a more user friendly manner. "noteWidth" -> "Note Spacing". It is difficult to understand the meaning of "defaultShift", it seems the same as "noteWidth". The other 2 are well named, but for the user it would be easier if the individual words had spaces between them.

6. Your group may also want to ensure that the measures are aligned so that each line in the score takes up the whole page width (as described in the 1st new requirement given after the midterm). Along with the upside down notes which are displayed underneath the guitar and bass tabs (you can see these using MuseScore and the "capricho.txt" musicXML output).

7. It would be useful to the user if the "stepSize" configuration has smaller options such as 3.0 or 2.5, so that more measures can be displayed on each line.

8. The music playing functionality may also be made available in the first screen where the tablature is given as input. Then the user would not need to preview music in order to also play the music.

These are simply some suggestions that I found will completing the bug-fixing task. The overall product seems to progressing at a good rate.

**Comment by CCSCovenant** [comment]
thanks for your suggestion!
you can check our new release 2.0
we take many of your suggestions!
