### ISSUE TITLE
Bug: Incorrect Triplet Sixteenth Notation on drumset sheet music 

### ISSUE THREAD

**Issue by kingsley9** [CCSCovenant/TAB2XML#24]
|Field   |      Value      | 
|:----------|:-------------|
| Title |  Incorrect Triplet Sixteenth Notation on drumset sheet music |
| Raised by | Kingsley Okon, King808@my.yorku.ca | 
| Description | When viewing sheet music display for drum tabs i found that the sixteenth triplet notes aren't correctly drawn or connected | 
| Version | [Pre Release 1.3](https://github.com/CCSCovenant/TAB2XML/tree/pre-release-1.3)  | 
| Platform | 1. OS: MacOS<br/> 2. Java: Java SE17 <br/> 3. Gradle: 7.3.3 <br/>4. IDE: Eclipse 4.22.0| 
| Steps to reproduce the issue | 1. Open the application <br/>2. Copy the [timingTest1.txt](https://github.com/kingsley9/Bug-report-files/blob/main/Tabs/timingTest1.txt) drumset tab<br/> 3. Paste the tab <br/>4. Click Preview Sheet Music button <br/> 5. Inspect measures with sisteenth triplet notes | 
| Expected result | Triplet Sixteenth notes drawn with correct notation   ![image](https://github.com/kingsley9/Bug-report-files/blob/main/Images/Screen%20Shot%202022-03-23%20at%207.26.10%20PM.png?raw=true)| 
| Actual result | Triplet Sixteenth notes drawn as normal sixteenth notes  ![image](https://github.com/kingsley9/Bug-report-files/blob/main/Images/Screen%20Shot%202022-03-23%20at%207.26.32%20PM.png?raw=true)| 
| Bug priority | Low | 
| Bug severity | Medium |

**Comment by CCSCovenant** [comment]
sorry, this feature is not intended to add in the project
