### ISSUE TITLE
Bug: Missing Note durations on guitar sheet music

### ISSUE THREAD

**Issue by kingsley9** [CCSCovenant/TAB2XML#25]
|Field   |      Value      | 
|:----------|:-------------|
| Title |  Missing Note durations on guitar sheet music |
| Raised by | Kingsley Okon, King808@my.yorku.ca | 
| Description | When viewing the sheet music display for guitar tabs i found that the durations of the notes which should be just under each staff is missing | 
| Version | [Pre Release 1.3](https://github.com/CCSCovenant/TAB2XML/tree/pre-release-1.3)  | 
| Platform | 1. OS: MacOS<br/> 2. Java: Java SE17 <br/> 3. Gradle: 7.3.3 <br/>4. IDE: Eclipse 4.22.0| 
| Steps to reproduce the issue | 1. Open the application <br/>2. Copy the [capricho.txt](https://github.com/kingsley9/Bug-report-files/blob/main/Tabs/capricho.txt) guitar tab<br/> 3. Paste the tab <br/>4. Click Preview Sheet Music button <br/> | 
| Expected result | Note durations under staff   ![image](https://github.com/kingsley9/Bug-report-files/blob/main/Images/Screen%20Shot%202022-03-23%20at%207.28.14%20PM.png?raw=true)| 
| Actual result | No Note duration  ![image](https://github.com/kingsley9/Bug-report-files/blob/main/Images/Screen%20Shot%202022-03-23%20at%207.28.25%20PM.png?raw=true)| 
| Bug priority | High | 
| Bug severity | Medium |

**Comment by CCSCovenant** [comment]
this bug has been fixed in 2.0 release
