### ISSUE TITLE
Bug: Incorrect Grace Note size on guitar sheet music

### ISSUE THREAD

**Issue by kingsley9** [CCSCovenant/TAB2XML#26]
|Field   |      Value      | 
|:----------|:-------------|
| Title |  Incorrect Grace Note size on guitar sheet music |
| Raised by | Kingsley Okon, King808@my.yorku.ca | 
| Description | When viewing the guitar sheet music the size of grace notes are the same as the size of regular notes  | 
| Version | [Pre Release 1.3](https://github.com/CCSCovenant/TAB2XML/tree/pre-release-1.3)   | 
| Platform | 1. OS: MacOS<br/> 2. Java: Java SE17 <br/> 3. Gradle: 7.3.3 <br/>4. IDE: Eclipse 4.22.0| 
| Steps to reproduce the issue | 1. Open the application <br/>2. Copy the [graceTest1.txt](https://github.com/kingsley9/Bug-report-files/blob/main/Tabs/graceTest1.txt) guitar tab<br/> 3. Paste the tab <br/>4. Click Preview Sheet Music button| 
| Expected result | Grace notes are visibly smaller than regular notes   ![image](https://github.com/kingsley9/Bug-report-files/blob/main/Images/Screen%20Shot%202022-03-23%20at%208.25.17%20PM.png?raw=true)| 
| Actual result | Grace notes are the same size as regular notes  ![image](https://github.com/kingsley9/Bug-report-files/blob/main/Images/Screen%20Shot%202022-03-23%20at%208.25.26%20PM.png?raw=true)| 
| Bug priority | Low | 
| Bug severity | Medium |

**Comment by CCSCovenant** [comment]
this bug has been fixed in 2.0 release
