### ISSUE TITLE
Incorrect music sheet preview testing with capricho.txt

### ISSUE THREAD

**Issue by lalazhang** [CCSCovenant/TAB2XML#27]
| Items  | Description |
| ------------- | ------------- |
| Who Raised | Lan  Zhang [zhalala8@my.yorku.ca](mailto:zhalala8@my.yorku.ca)  |
| Version | pre release 1.3 |
| Reproduction | 1. Run the Application by Gradle Tasks->appllication->run  2. On the interface, select File and Open.. /Your Project Folder Path/src/test/resources/system/capricho.txt| 
| Platform| macOs  Monterey Version12.0.1,    JavaSE-17 , Graddle 7.3.1|
|Expected Outcome| <img width="663" alt="Screen Shot 2022-03-23 at 10 28 29 PM" src="https://user-images.githubusercontent.com/37859728/159830990-15e809b7-2c19-4c2f-9a94-744ab0249344.png"> |
|Actual Outcome|<img width="766" alt="Screen Shot 2022-03-23 at 10 28 08 PM" src="https://user-images.githubusercontent.com/37859728/159831019-c5dfb581-89ba-45a1-99de-5700c2b27068.png"> 6--8 inserted  |
| Priority | 7/10 music note accuracy is important feature of this App|
| Severity | 1/10 minor inaccuracy |

**Comment by CCSCovenant** [comment]
this bug has been fixed in 2.0 release
