### ISSUE TITLE
Incomplete music score display testing on capricho.txt

### ISSUE THREAD

**Issue by lalazhang** [CCSCovenant/TAB2XML#28]
| Items  | Description |
| ------------- | ------------- |
| Who Raised | Lan  Zhang [zhalala8@my.yorku.ca](mailto:zhalala8@my.yorku.ca)  |
| Version | pre release 1.3 |
| Reproduction | 1. Run the Application by Gradle Tasks->appllication->run  2. On the interface, select File and Open.. /Your Project Folder Path/src/test/resources/system/capricho.txt| 
| Platform| macOs  Monterey Version12.0.1,    JavaSE-17 , Graddle 7.3.1|
|Expected Outcome| <img width="736" alt="Screen Shot 2022-03-23 at 10 33 23 PM" src="https://user-images.githubusercontent.com/37859728/159833270-4865820b-f3fc-4b0d-95a9-d2afd6cdb417.png"> There are about 70 sections of music notes |
|Actual Outcome|<img width="1112" alt="Screen Shot 2022-03-23 at 10 34 01 PM" src="https://user-images.githubusercontent.com/37859728/159833332-3a6c63ca-49c0-43d5-aaa8-b5ca9b222bff.png"> The Preview Music Sheet displays 1/4 of the full music score|
| Priority | 5/10 The difficulty of implementing this feature is understandable since capicho.txt is lengthy text |
| Severity | 2/10 The severity isn't high since its not a malfunction instead of non finished feature  |

**Comment by CCSCovenant** [comment]
you didn't go to the next page!!!!!
