### ISSUE TITLE
Partially incorrect music sheet conversion

### ISSUE THREAD

**Issue by Le-Hieu-216276412** [CCSCovenant/TAB2XML#29]
**Description:**
The problem occurs when I try to convert graceTest2.txt. On the leftmost of the music sheet there is a number "1" and no number is supposed to be there in the expected conversion. Additionally, the music sheet lacks the special notation at the bottom and the slur notations aren't placed correctly.

**Version:**
Branch: master
Git commit version: pre-release 1.3

**Required input**
[graceTest2.txt](https://github.com/CCSCovenant/TAB2XML/files/8338049/graceTest2.txt)

**Steps to reproduce**
1. Run the application via Gradle task

2. Copy and paste the text file as the input

3. Press SaveMusicXML to convert to an xml file

4. Open the new xml file on MuseScore. Meanwhile, press Preview Sheet Music on the Gradle application

5. Compare the 2 results

**Expected output**
<img width="574" alt="Screen Shot 2022-03-23 at 22 57 08" src="https://user-images.githubusercontent.com/46415630/159833057-8f540012-8fe0-43b6-852f-8c88ab7af92f.png">

**Actual output**
The blue circle is the said "1" that is not supposed to be there. The green marks indicate the expected position of the slur notation and the red marks are the missing notation

<img width="755" alt="Screen Shot 2022-03-23 at 22 57 37" src="https://user-images.githubusercontent.com/46415630/159833461-0ef11fe3-bff7-480b-9163-f0c834e622c8.png">

**Severity: Medium**
The program runs well but the incorrect conversion will cause the song to be played differently

**Priority: Medium**
The special notations are most likely a case of unfinished implementation and while it won't do much harm at this stage, it should be fixed the sooner the better. As for the number at the edge of the music sheet, while it may just be a way to mark a measure number, I'd suggest placing the number a bit further from the sheet or make it clear that the number has nothing to do with the conversion. The idea of marking number is great but make it clearer and the user experience will be greatly improved

**Comment by CCSCovenant** [comment]
this bug has been fixed in 2.0 release
