### ISSUE TITLE
Incomplete implementation of music score preview with parabola.txt

### ISSUE THREAD

**Issue by lalazhang** [CCSCovenant/TAB2XML#30]
| Items  | Description |
| ------------- | ------------- |
| Who Raised | Lan  Zhang [zhalala8@my.yorku.ca](mailto:zhalala8@my.yorku.ca)  |
| Version | pre release 1.3 |
| Reproduction | 1. Run the Application by Gradle Tasks->appllication->run  2. On the interface, select File and Open.. /Your Project Folder Path/src/test/resources/system/capricho.txt| 
| Platform| macOs  Monterey Version12.0.1,    JavaSE-17 , Graddle 7.3.1|
|Expected Outcome|<img width="589" alt="Screen Shot 2022-03-23 at 11 25 38 PM" src="https://user-images.githubusercontent.com/37859728/159836289-944f3698-4df7-42c5-9166-4dc0b9460fb5.png"> |
|Actual Outcome| The implementation shows up to 9 sections which is about 1/10 of the full script  <img width="1112" alt="Screen Shot 2022-03-23 at 11 25 22 PM" src="https://user-images.githubusercontent.com/37859728/159836406-fe1b5b5f-cf61-470b-8ea9-2351c07e6a72.png">|
| Priority | 5/10 With lengthy XML the notes should still be displayed |
| Severity | 1/10 It's more of incomplete implementation rather than an error |

**Comment by CCSCovenant** [comment]
it is not a bug.
you didn't go to next page
