### ISSUE TITLE
Pdf conversion not working properly

### ISSUE THREAD

**Issue by Le-Hieu-216276412** [CCSCovenant/TAB2XML#31]
**Description:**
When I save a converted music sheet as pdf, the pdf prints out the music sheet correctly except for the measure number. Take the capricho.txt file for example, the converted sheet mark the end of  the measures at number 73 on the app. However, when it is converted to a pdf version, the number marking function keeps counting on ( instead of 1, the mark on pdf will 74, 2 becomes 75 and so on)

**Version:**
branch: master
git commit version: pre-release 1.3

**Required input**
[capricho.txt](https://github.com/CCSCovenant/TAB2XML/files/8338237/capricho.txt)

**Steps to reproduce**

1. Run the application via Gradle task

2. Copy and paste the text file as the input

3. Press Preview Sheet Music -> Save PDF

4. Open the new pdf file and compare the result

**Expected output** (screenshot of the first 3 numbers)

<img width="805" alt="Screen Shot 2022-03-23 at 23 41 33" src="https://user-images.githubusercontent.com/46415630/159837651-c1bb0685-2ed4-453c-b8c0-361e27337861.png">

**Actual output**

<img width="509" alt="Screen Shot 2022-03-23 at 23 42 20" src="https://user-images.githubusercontent.com/46415630/159837732-e9fd7dc1-29ee-439c-ac9d-963d954d6e65.png">

**Severity: Low**

**Priority: Low**

**Comment by CCSCovenant** [comment]
this bug has been fixed in 2.0 release
