### ISSUE TITLE
Wrong notes demonstration on parabola.txt

### ISSUE THREAD

**Issue by Le-Hieu-216276412** [CCSCovenant/TAB2XML#32]
**Description**
All the notes in parabola.txt are demonstrated in the right positions but wrong notations

**Version:**
branch: master
git commit version: pre-release 1.3

**Required input**
[parabola copy.txt](https://github.com/CCSCovenant/TAB2XML/files/8338297/parabola.copy.txt)

** Steps to reproduce:**

Run the application via Gradle task

Copy and paste the text file as the input

Press SaveMusicXML to convert to an xml file

Open the new xml file on MuseScore. Meanwhile, press Preview Sheet Music on the Gradle application

Compare the 2 results

**Expected Output** (screenshot of first 2 lines)
<img width="693" alt="Screen Shot 2022-03-23 at 23 53 02" src="https://user-images.githubusercontent.com/46415630/159838829-444ea036-fb4f-4177-a06c-6dca06aec249.png">

**Actual Output**
<img width="936" alt="Screen Shot 2022-03-23 at 23 54 08" src="https://user-images.githubusercontent.com/46415630/159838955-7e569332-3912-4552-8ec8-6946b1e88d91.png">

**Severity: Medium**
This is a different note so the song will play differently

**Priority: Medium**
This is most likely a case of unfinished implementation and while it won't do much harm at this stage, it should be fixed the sooner the better

**Comment by CCSCovenant** [comment]
this bug has been fixed in 2.0 release
